import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutterblog/conf/config.dart';
import 'package:flutterblog/conf/const.dart';

class HomePage extends StatefulWidget {
  HomePage({this.home, Key key, this.title}) : super(key: key);

  final Widget title;
  final Widget home;
  List<Autogenerated> listData = [];

  @override
  State<StatefulWidget> createState() => _HomePage();
}

class _HomePage extends State<HomePage> {
  initState() {
    super.initState();
    getHttp();
  }

  @override
  Widget build(BuildContext context) {
//    for (int i = 0; i < 20; i++) {
//      widget.listData.add( Autogenerated());
//    }

    return ListView.builder(
      shrinkWrap: true,
      itemBuilder: (BuildContext context, int index) {
        return ListItemWidget(widget.listData[index]);
      },
      itemCount: widget.listData.length,
    );
  }

  Future getHttp() async {
    Dio dio = new Dio();
    try {
      debugPrint("${githubApi}repos/$user/$repo/contents/$blogPath");
      Response response = await dio.get(
          "${githubApi}repos/$user/$repo/contents/$blogPath",
          options: Options(responseType: ResponseType.json));
      print(response.data);
      List<dynamic> newTitle = response.data;

      setState(() {
        newTitle.forEach((value) {
          debugPrint(value.toString());
          widget.listData.add(Autogenerated.fromJson(value));
        });
      });
//        listData.add(Autogenerated.);
//       ListItem.fromJson(_parseAndDecode(response.data));
      return response.data;
    } catch (e) {
      return print(e);
    }
  }
}

class ListItemWidget extends StatelessWidget {
  final Autogenerated listItem;

  ListItemWidget(this.listItem);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      child: ConstrainedBox(
        constraints: BoxConstraints(
            minWidth: double.infinity, //宽度尽可能大
            minHeight: 120.0 //最小高度为50像素
            ),
        child: Padding(
          padding: EdgeInsets.only(left: 120, top: 20),
          child: Text(
            listItem.name,
            style: TextStyle(color: Colors.black, fontSize: 30),
          ),
        ),
      ),
      onTap: () {},
    );
  }
}

class Autogenerated {
  String name;
  String path;
  String sha;
  int size;
  String url;
  String htmlUrl;
  String gitUrl;
  String downloadUrl;
  String type;
  Links lLinks;

  Autogenerated(
      {this.name,
      this.path,
      this.sha,
      this.size,
      this.url,
      this.htmlUrl,
      this.gitUrl,
      this.downloadUrl,
      this.type,
      this.lLinks});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    path = json['path'];
    sha = json['sha'];
    size = json['size'];
    url = json['url'];
    htmlUrl = json['html_url'];
    gitUrl = json['git_url'];
    downloadUrl = json['download_url'];
    type = json['type'];
    lLinks = json['_links'] != null ? new Links.fromJson(json['_links']) : null;
  }
}

class Links {
  String self;
  String git;
  String html;

  Links({this.self, this.git, this.html});

  Links.fromJson(Map<String, dynamic> json) {
    self = json['self'];
    git = json['git'];
    html = json['html'];
  }
}
